// src/constants/phLocations.js

export const PH_REGIONS = [
  'National Capital Region (NCR)',
  'Region I (Ilocos Region)',
  'Region II (Cagayan Valley)',
  'Region III (Central Luzon)',
  'Region IV-A (CALABARZON)',
  'Region IV-B (MIMAROPA)',
  'Region V (Bicol Region)',
  'Region VI (Western Visayas)',
  'Region VII (Central Visayas)',
  'Region VIII (Eastern Visayas)',
  'Negros Island Region (NIR)',
  'Region IX (Zamboanga Peninsula)',
  'Region X (Northern Mindanao)',
  'Region XI (Davao Region)',
  'Region XII (SOCCSKSARGEN)',
  'Region XIII (Caraga)',
  'Cordillera Administrative Region (CAR)',
  'Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)',
];

export const PH_PROVINCES_BY_REGION = {
  'National Capital Region (NCR)': ['Metro Manila'],

  'Region I (Ilocos Region)': [
    'Ilocos Norte',
    'Ilocos Sur',
    'La Union',
    'Pangasinan',
  ],

  'Region II (Cagayan Valley)': [
    'Batanes',
    'Cagayan',
    'Isabela',
    'Nueva Vizcaya',
    'Quirino',
  ],

  'Region III (Central Luzon)': [
    'Aurora',
    'Bataan',
    'Bulacan',
    'Nueva Ecija',
    'Pampanga',
    'Tarlac',
    'Zambales',
  ],

  'Region IV-A (CALABARZON)': [
    'Batangas',
    'Cavite',
    'Laguna',
    'Quezon',
    'Rizal',
  ],

  'Region IV-B (MIMAROPA)': [
    'Marinduque',
    'Occidental Mindoro',
    'Oriental Mindoro',
    'Palawan',
    'Romblon',
  ],

  'Region V (Bicol Region)': [
    'Albay',
    'Camarines Norte',
    'Camarines Sur',
    'Catanduanes',
    'Masbate',
    'Sorsogon',
  ],

  'Region VI (Western Visayas)': [
    'Aklan',
    'Antique',
    'Capiz',
    'Guimaras',
    'Iloilo',
    'Negros Occidental',
  ],

  'Region VII (Central Visayas)': [
    'Bohol',
    'Cebu',
    'Negros Oriental',
    'Siquijor',
  ],

  'Region VIII (Eastern Visayas)': [
    'Biliran',
    'Eastern Samar',
    'Leyte',
    'Northern Samar',
    'Samar',
    'Southern Leyte',
  ],

  'Negros Island Region (NIR)': [
    'Negros Occidental',
    'Negros Oriental',
  ],

  'Region IX (Zamboanga Peninsula)': [
    'Zamboanga del Norte',
    'Zamboanga del Sur',
    'Zamboanga Sibugay',
  ],

  'Region X (Northern Mindanao)': [
    'Bukidnon',
    'Camiguin',
    'Lanao del Norte',
    'Misamis Occidental',
    'Misamis Oriental',
  ],

  'Region XI (Davao Region)': [
    'Davao de Oro',
    'Davao del Norte',
    'Davao del Sur',
    'Davao Occidental',
    'Davao Oriental',
  ],

  'Region XII (SOCCSKSARGEN)': [
    'Cotabato',
    'Sarangani',
    'South Cotabato',
    'Sultan Kudarat',
  ],

  'Region XIII (Caraga)': [
    'Agusan del Norte',
    'Agusan del Sur',
    'Dinagat Islands',
    'Surigao del Norte',
    'Surigao del Sur',
  ],

  'Cordillera Administrative Region (CAR)': [
    'Abra',
    'Apayao',
    'Benguet',
    'Ifugao',
    'Kalinga',
    'Mountain Province',
  ],

  'Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)': [
    'Basilan',
    'Lanao del Sur',
    'Maguindanao del Norte',
    'Maguindanao del Sur',
    'Sulu',
    'Tawi-Tawi',
  ],
};

export const PH_CITIES_BY_PROVINCE = {
  'Metro Manila': [
    'Caloocan',
    'Las Piñas',
    'Makati',
    'Malabon',
    'Mandaluyong',
    'Manila',
    'Marikina',
    'Muntinlupa',
    'Navotas',
    'Parañaque',
    'Pasay',
    'Pasig',
    'Pateros',
    'Quezon City',
    'San Juan',
    'Taguig',
    'Valenzuela',
  ],

  Aurora: [
    'Baler',
    'Casiguran',
    'Dilasag',
    'Dinalungan',
    'Dingalan',
    'Dipaculao',
    'Maria Aurora',
    'San Luis',
  ],

  Bataan: [
    'Abucay',
    'Bagac',
    'Balanga City',
    'Dinalupihan',
    'Hermosa',
    'Limay',
    'Mariveles',
    'Morong',
    'Orani',
    'Orion',
    'Pilar',
    'Samal',
  ],

  Bulacan: [
    'Angat',
    'Balagtas',
    'Baliuag',
    'Bocaue',
    'Bulakan',
    'Bustos',
    'Calumpit',
    'Doña Remedios Trinidad',
    'Guiguinto',
    'Hagonoy',
    'Malolos City',
    'Marilao',
    'Meycauayan City',
    'Norzagaray',
    'Obando',
    'Pandi',
    'Paombong',
    'Plaridel',
    'Pulilan',
    'San Ildefonso',
    'San Jose del Monte City',
    'San Miguel',
    'San Rafael',
    'Santa Maria',
  ],

  'Nueva Ecija': [
    'Aliaga',
    'Bongabon',
    'Cabanatuan City',
    'Cabiao',
    'Carranglan',
    'Cuuyapo',
    'Gabaldon',
    'Gapan City',
    'General Mamerto Natividad',
    'General Tinio',
    'Guimba',
    'Jaen',
    'Laur',
    'Licab',
    'Llanera',
    'Lupao',
    'Muñoz City',
    'Nampicuan',
    'Palayan City',
    'Pantabangan',
    'Peñaranda',
    'Quezon',
    'Rizal',
    'San Antonio',
    'San Isidro',
    'San Jose City',
    'San Leonardo',
    'Santa Rosa',
    'Santo Domingo',
    'Talavera',
    'Talugtug',
    'Zaragoza',
  ],

  Pampanga: [
    'Angeles City',
    'Apalit',
    'Arayat',
    'Bacolor',
    'Candaba',
    'Floridablanca',
    'Guagua',
    'Lubao',
    'Mabalacat City',
    'Macabebe',
    'Magalang',
    'Masantol',
    'Mexico',
    'Minalin',
    'Porac',
    'San Fernando City',
    'San Luis',
    'San Simon',
    'Santa Ana',
    'Santa Rita',
    'Santo Tomas',
    'Sasmuan',
  ],

  Tarlac: [
    'Anao',
    'Bamban',
    'Camiling',
    'Capas',
    'Concepcion',
    'Gerona',
    'La Paz',
    'Mayantoc',
    'Moncada',
    'Paniqui',
    'Pura',
    'Ramos',
    'San Clemente',
    'San Jose',
    'San Manuel',
    'Santa Ignacia',
    'Tarlac City',
    'Victoria',
  ],

  Zambales: [
    'Botolan',
    'Cabangan',
    'Candelaria',
    'Castillejos',
    'Iba',
    'Masinloc',
    'Olongapo City',
    'Palauig',
    'San Antonio',
    'San Felipe',
    'San Marcelino',
    'San Narciso',
    'Santa Cruz',
    'Subic',
  ],

  Rizal: [
    'Angono',
    'Antipolo City',
    'Baras',
    'Binangonan',
    'Cainta',
    'Cardona',
    'Jalajala',
    'Morong',
    'Pililla',
    'Rodriguez',
    'San Mateo',
    'Tanay',
    'Taytay',
    'Teresa',
  ],

  Cavite: [
    'Alfonso',
    'Amadeo',
    'Bacoor City',
    'Carmona',
    'Cavite City',
    'Dasmariñas City',
    'General Emilio Aguinaldo',
    'General Mariano Alvarez',
    'General Trias City',
    'Imus City',
    'Indang',
    'Kawit',
    'Magallanes',
    'Maragondon',
    'Mendez',
    'Naic',
    'Noveleta',
    'Rosario',
    'Silang',
    'Tagaytay City',
    'Tanza',
    'Ternate',
    'Trece Martires City',
  ],

  Laguna: [
    'Alaminos',
    'Bay',
    'Biñan City',
    'Cabuyao City',
    'Calamba City',
    'Calauan',
    'Cavinti',
    'Famy',
    'Kalayaan',
    'Liliw',
    'Los Baños',
    'Luisiana',
    'Lumban',
    'Mabitac',
    'Magdalena',
    'Majayjay',
    'Nagcarlan',
    'Paete',
    'Pagsanjan',
    'Pakil',
    'Pangil',
    'Pila',
    'Rizal',
    'San Pablo City',
    'San Pedro City',
    'Santa Cruz',
    'Santa Maria',
    'Santa Rosa City',
    'Siniloan',
    'Victoria',
  ],

  Batangas: [
    'Agoncillo',
    'Alitagtag',
    'Balayan',
    'Balete',
    'Batangas City',
    'Bauan',
    'Calaca',
    'Calatagan',
    'Cuenca',
    'Ibaan',
    'Laurel',
    'Lemery',
    'Lian',
    'Lipa City',
    'Lobo',
    'Mabini',
    'Malvar',
    'Mataasnakahoy',
    'Nasugbu',
    'Padre Garcia',
    'Rosario',
    'San Jose',
    'San Juan',
    'San Luis',
    'San Nicolas',
    'San Pascual',
    'Santa Teresita',
    'Santo Tomas City',
    'Taal',
    'Talisay',
    'Tanauan City',
    'Taysan',
    'Tingloy',
    'Tuy',
  ],

  Quezon: [
    'Agdangan',
    'Alabat',
    'Atimonan',
    'Buenavista',
    'Burdeos',
    'Calauag',
    'Candelaria',
    'Catanauan',
    'Dolores',
    'General Luna',
    'General Nakar',
    'Guinayangan',
    'Gumaca',
    'Infanta',
    'Jomalig',
    'Lopez',
    'Lucban',
    'Lucena City',
    'Macalelon',
    'Mauban',
    'Mulanay',
    'Pagbilao',
    'Panukulan',
    'Patnanungan',
    'Perez',
    'Pitogo',
    'Plaridel',
    'Polillo',
    'Quezon',
    'Real',
    'Sampaloc',
    'San Andres',
    'San Antonio',
    'San Francisco',
    'San Narciso',
    'Sariaya',
    'Tagkawayan',
    'Tayabas City',
    'Tiaong',
    'Unisan',
  ],
};

// Backward compatibility for existing employer pages
export const PH_CITIES_BY_REGION = {
  'National Capital Region (NCR)': PH_CITIES_BY_PROVINCE['Metro Manila'] || [],
  'Region I (Ilocos Region)': PH_PROVINCES_BY_REGION['Region I (Ilocos Region)'] || [],
  'Region II (Cagayan Valley)': PH_PROVINCES_BY_REGION['Region II (Cagayan Valley)'] || [],
  'Region III (Central Luzon)': PH_PROVINCES_BY_REGION['Region III (Central Luzon)'] || [],
  'Region IV-A (CALABARZON)': PH_PROVINCES_BY_REGION['Region IV-A (CALABARZON)'] || [],
  'Region IV-B (MIMAROPA)': PH_PROVINCES_BY_REGION['Region IV-B (MIMAROPA)'] || [],
  'Region V (Bicol Region)': PH_PROVINCES_BY_REGION['Region V (Bicol Region)'] || [],
  'Region VI (Western Visayas)': PH_PROVINCES_BY_REGION['Region VI (Western Visayas)'] || [],
  'Region VII (Central Visayas)': PH_PROVINCES_BY_REGION['Region VII (Central Visayas)'] || [],
  'Region VIII (Eastern Visayas)': PH_PROVINCES_BY_REGION['Region VIII (Eastern Visayas)'] || [],
  'Negros Island Region (NIR)': PH_PROVINCES_BY_REGION['Negros Island Region (NIR)'] || [],
  'Region IX (Zamboanga Peninsula)': PH_PROVINCES_BY_REGION['Region IX (Zamboanga Peninsula)'] || [],
  'Region X (Northern Mindanao)': PH_PROVINCES_BY_REGION['Region X (Northern Mindanao)'] || [],
  'Region XI (Davao Region)': PH_PROVINCES_BY_REGION['Region XI (Davao Region)'] || [],
  'Region XII (SOCCSKSARGEN)': PH_PROVINCES_BY_REGION['Region XII (SOCCSKSARGEN)'] || [],
  'Region XIII (Caraga)': PH_PROVINCES_BY_REGION['Region XIII (Caraga)'] || [],
  'Cordillera Administrative Region (CAR)': PH_PROVINCES_BY_REGION['Cordillera Administrative Region (CAR)'] || [],
  'Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)': PH_PROVINCES_BY_REGION['Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)'] || [],
};