// src/constants/technicalSkills.js
export const TECHNICAL_SKILLS = [
  "Figma",
  "MS Word",
  "MS Excel",
  "MS PowerPoint",
  "Canva",
  "Google Docs",
  "Google Sheets",
  "Google Slides",
  "JavaScript",
  "React",
  "Node.js",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "MongoDB",
  "SQL",
  "UI/UX",
  "Graphic Design",
  "Video Editing",
  "Photo Editing",
  "Customer Service",
  "Accounting",
  "Housekeeping",
  "Food & Beverage",
  "Data Entry",
  "Typing",
];