import React, { useEffect, useState } from 'react';
import { ArrowLeft, Check, Clock, X } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import api from '../../services/api';

const date = (value, withTime = false) => value ? new Date(value).toLocaleString('en-PH', withTime ? { dateStyle: 'medium', timeStyle: 'short' } : { dateStyle: 'medium' }) : '—';
const name = (user = {}) => user.fullName || [user.firstName, user.middleName, user.lastName].filter(Boolean).join(' ') || '—';
const reason = (value) => value === 'contract_ended' ? 'Contract Ended' : 'Employment Ended';
const duration = (item) => { const start = new Date(item.hiredAt || item.reviewedAt); const end = item.employmentEndedAt ? new Date(item.employmentEndedAt) : new Date(); if (Number.isNaN(start.getTime())) return '—'; const days = Math.max(0, Math.floor((end-start)/86400000)); return days < 30 ? `${days} days` : `${Math.floor(days/30)} months and ${days%30} days`; };

export default function AdminJobseekerRequestDetails() {
  const { jobseekerId, requestId } = useParams();
  const navigate = useNavigate();
  const [request, setRequest] = useState(null);
  const [error, setError] = useState('');
  const [confirm, setConfirm] = useState('');
  const [saving, setSaving] = useState(false);
  const [success, setSuccess] = useState('');
  const load = () => api.get(`/applications/admin/employment-status-requests/jobseeker/${jobseekerId}/${requestId}`).then(({data})=>setRequest(data.request)).catch(err=>setError(err.response?.data?.message || 'Unable to load request.'));
  useEffect(load, [jobseekerId, requestId]);
  const decide = async () => { try { setSaving(true); const {data}=await api.put(`/applications/admin/employment-status-requests/${requestId}/final-decision`, { decision: confirm }); setRequest(data.application); setSuccess(confirm === 'approved' ? "Request Approved Successfully\nThe job seeker's employment status request has been approved." : "Request Declined Successfully\nThe job seeker's employment status request has been declined."); setConfirm(''); } catch(err){ setError(err.response?.data?.message || 'Unable to save decision.'); } finally { setSaving(false); } };
  if (!request) return <div className="p-10 text-center">{error || 'Loading request...'}</div>;
  const statusRequest = request.employmentStatusRequest || {};
  const employerResponse = statusRequest.employerResponse || {};
  const adminDecision = statusRequest.adminDecision || {};
  const employerAnswered = ['approved','declined','no_response'].includes(employerResponse.decision) || statusRequest.status === 'no_response';
  const final = ['approved','declined'].includes(adminDecision.decision);
  const status = final ? adminDecision.decision : statusRequest.status;
  return <div className="mx-auto max-w-[1450px] space-y-5 py-8">
    <header className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><button onClick={()=>navigate(`/admin/jobseeker-status-requests/${jobseekerId}`)} className="rounded-xl border bg-white p-3"><ArrowLeft size={18}/></button><div><h1 className="text-2xl font-bold">Job Seeker Request</h1><p className="text-sm text-slate-500">Review the details below and take action on the request.</p></div></div><div className="flex gap-3"><button disabled={!employerAnswered || final} onClick={()=>setConfirm('approved')} className="rounded-xl bg-emerald-600 px-5 py-3 font-semibold text-white disabled:bg-slate-300"><Check className="mr-2 inline" size={17}/>Approve Request</button><button disabled={!employerAnswered || final} onClick={()=>setConfirm('declined')} className="rounded-xl bg-red-600 px-5 py-3 font-semibold text-white disabled:bg-slate-300"><X className="mr-2 inline" size={17}/>Decline Request</button></div></header>
    <section className="grid gap-4 rounded-2xl border bg-white p-5 shadow-sm md:grid-cols-5"><Info label="Jobseeker" value={name(request.jobseeker)} sub={request.jobseeker?.email}/><Info label="Requested Date" value={date(statusRequest.requestedAt)}/><Info label="Company" value={request.job?.companyName || request.employer?.employerProfile?.companyName}/><Info label="Job Title" value={request.job?.title}/><Info label="Request" value={reason(statusRequest.reason)}/></section>
    <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="mb-5 font-bold text-emerald-700">Employment Details</h2><Rows values={[["Industry",request.job?.industry || request.employer?.employerProfile?.industry],["Applied Date",date(request.appliedAt)],["Date Hired",date(request.hiredAt || request.reviewedAt)],["Employment Duration",duration(request)],["Current Status",request.employmentStatus === 'inactive' ? 'Inactive' : 'Active']]}/></section>
    <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="mb-3 text-xl font-bold capitalize">{status.replace('_',' ')}</h2><p className="mb-5 text-slate-600">{status === 'pending' ? 'Waiting for the employer to respond to this request.' : status === 'no_response' ? 'No response received. The employer did not respond to this request within 7 days.' : `The request has been ${status}.`}</p><Rows values={[[employerResponse.decision === 'declined' ? 'Declined By' : 'Responded By',name(employerResponse.respondedBy || request.employer)],["Employer Email",employerResponse.respondedBy?.email || request.employer?.email],["Response Date & Time",date(employerResponse.respondedAt,true)],...(employerResponse.decision === 'declined' ? [["Reason",employerResponse.declineReason],["Explanation",employerResponse.explanation]] : []),...(final ? [[adminDecision.decision === 'approved' ? 'Approved By' : 'Declined By',name(adminDecision.decidedBy)],["Admin Email",adminDecision.decidedBy?.email],["Final Decision Date",date(adminDecision.decidedAt,true)]] : [])]}/></section></div>
    {confirm && <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-bold capitalize">{confirm} Request?</h2><p className="mt-3 text-slate-600">{confirm === 'approved' ? "Are you sure you want to approve this request to end the job seeker's current employment status? The status will change from Active to Inactive." : "Are you sure you want to decline the job seeker's request? The current employment status will remain Active."}</p><p className="mt-4 rounded-xl bg-slate-50 p-4"><b>Request Reason:</b> {reason(statusRequest.reason)}</p><div className="mt-5 grid grid-cols-2 gap-3"><button onClick={()=>setConfirm('')} className="rounded-xl border py-3 font-semibold">Cancel</button><button disabled={saving} onClick={decide} className={`rounded-xl py-3 font-semibold text-white ${confirm === 'approved' ? 'bg-[#2e66a6]' : 'bg-red-600'}`}>{saving ? 'Processing...' : `${confirm === 'approved' ? 'Approve' : 'Decline'} Request`}</button></div></div></div>}
    {success && <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-7 text-center shadow-2xl"><Check className="mx-auto text-emerald-600" size={42}/>{success.split('\n').map(line=><p key={line} className="mt-3 first:text-xl first:font-bold">{line}</p>)}<button onClick={()=>setSuccess('')} className="mt-5 rounded-xl bg-[#2e66a6] px-8 py-3 font-semibold text-white">Close</button></div></div>}
  </div>;
}
const Info=({label,value,sub})=><div><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-2 font-semibold">{value || '—'}</p>{sub&&<p className="text-xs text-slate-500">{sub}</p>}</div>;
const Rows=({values})=><div className="space-y-3">{values.map(([label,value])=><div key={label} className="grid grid-cols-[150px_1fr] gap-3 border-b pb-3 text-sm"><span className="text-slate-500">{label}</span><span className="font-medium">{value || '—'}</span></div>)}</div>;
